language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-eggs-genny' ]; then cd .. && eval "mv $currentfolder generator-eggs-genny" && cd generator-eggs-genny; fi

